'use client';

import { useEffect, useState } from 'react';
import { apiRequest } from '../api-client';
import { useDashboard } from './dashboard-context';

type Analytics = { kpis: { totalConversations: number; aiResolved: number; humanHandoffs: number; averageResponseTimeSeconds: number | null; activeDocuments: number; activeAgents: number }; conversationsOverTime: Array<{ date: string; total: number; ai: number; human: number }>; tokenUsage: { inputTokens: number; outputTokens: number; totalTokens: number }; knowledge: { retrievalSuccessRate: number | null; failedRetrievals: number }; inbox: { open: number; assigned: number; closed: number } };
const formatNumber = (value: number): string => value.toLocaleString();

export function AnalyticsDashboard() {
  const { currentWorkspace, loading: workspaceLoading, error: workspaceError, reload } = useDashboard();
  const [analytics, setAnalytics] = useState<Analytics | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = () => { if (!currentWorkspace) { setAnalytics(null); setLoading(false); return; } setLoading(true); setError(''); void apiRequest<Analytics>(`/workspaces/${currentWorkspace.id}/analytics`).then(setAnalytics).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'Unable to load analytics.')).finally(() => setLoading(false)); };
  useEffect(load, [currentWorkspace]);
  if (workspaceLoading || loading) return <section className="analytics-page"><p className="dashboard-inline-status">Loading analytics…</p></section>;
  if (workspaceError) return <section className="analytics-page"><div className="dashboard-error" role="alert"><span>{workspaceError}</span><button type="button" onClick={() => void reload()}>Try again</button></div></section>;
  if (error) return <section className="analytics-page"><div className="dashboard-error" role="alert"><span>{error}</span><button type="button" onClick={load}>Try again</button></div></section>;
  if (!analytics) return <section className="analytics-page"><div className="analytics-empty"><p className="eyebrow">Analytics</p><h2>Select a workspace to see performance.</h2></div></section>;
  const maxDay = Math.max(...analytics.conversationsOverTime.map((item) => item.total), 1);
  const cards = [['Total conversations', formatNumber(analytics.kpis.totalConversations)], ['AI resolved', formatNumber(analytics.kpis.aiResolved)], ['Human handoffs', formatNumber(analytics.kpis.humanHandoffs)], ['Avg response time', analytics.kpis.averageResponseTimeSeconds === null ? '—' : `${analytics.kpis.averageResponseTimeSeconds.toFixed(1)}s`], ['Active documents', formatNumber(analytics.kpis.activeDocuments)], ['Active AI agents', formatNumber(analytics.kpis.activeAgents)]];
  return <section className="analytics-page"><div className="analytics-heading"><div><p className="eyebrow">Workspace analytics</p><h2>See how your support system is performing.</h2><p>Live activity and usage for {currentWorkspace?.name ?? 'this workspace'} over the last 30 days.</p></div><span className="analytics-range">Last 30 days</span></div><div className="analytics-kpi-grid">{cards.map(([label, value]) => <div className="analytics-kpi" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="analytics-panels"><article className="analytics-panel analytics-chart-panel"><div className="section-heading"><div><p className="eyebrow">Conversations</p><h3>Activity over time</h3></div><span className="section-hint">AI vs human</span></div><div className="analytics-bars" aria-label="Conversations over time chart">{analytics.conversationsOverTime.length === 0 ? <p className="analytics-muted">No conversations in this period.</p> : analytics.conversationsOverTime.map((item) => <div className="analytics-bar-column" key={item.date}><div className="analytics-bar-stack" title={`${item.date}: ${item.total} conversations`}><i className="analytics-bar-ai" style={{ height: `${(item.ai / maxDay) * 100}%` }} /><i className="analytics-bar-human" style={{ height: `${(item.human / maxDay) * 100}%` }} /></div><small>{item.date.slice(5)}</small></div>)}</div><div className="analytics-legend"><span><i className="analytics-bar-ai" /> AI</span><span><i className="analytics-bar-human" /> Human</span></div></article><article className="analytics-panel"><div className="section-heading"><div><p className="eyebrow">Usage</p><h3>Tokens consumed</h3></div></div><div className="analytics-token-total">{formatNumber(analytics.tokenUsage.totalTokens)}<small>total tokens</small></div><div className="analytics-token-row"><span>Input tokens</span><strong>{formatNumber(analytics.tokenUsage.inputTokens)}</strong></div><div className="analytics-token-row"><span>Output tokens</span><strong>{formatNumber(analytics.tokenUsage.outputTokens)}</strong></div></article></div><div className="analytics-panels analytics-secondary"><article className="analytics-panel"><p className="eyebrow">Knowledge</p><h3>Retrieval quality</h3><div className="analytics-secondary-value">{analytics.knowledge.retrievalSuccessRate === null ? '—' : `${Math.round(analytics.knowledge.retrievalSuccessRate * 100)}%`}<small>success rate</small></div><p className="analytics-muted">{analytics.knowledge.failedRetrievals} failed retrievals in this period.</p></article><article className="analytics-panel"><p className="eyebrow">Inbox</p><h3>Conversation status</h3><div className="analytics-status-grid"><div><strong>{analytics.inbox.open}</strong><span>Open</span></div><div><strong>{analytics.inbox.assigned}</strong><span>Assigned</span></div><div><strong>{analytics.inbox.closed}</strong><span>Closed</span></div></div></article></div></section>;
}
