'use client';

import Link from 'next/link';
import { useSearchParams, useRouter } from 'next/navigation';
import { Suspense, useState, type FormEvent } from 'react';
import { apiRequest } from '../api-client';
import { ResolveAILogo } from '../resolveai-logo';

function ResetPasswordContent() { const params = useSearchParams(); const router = useRouter(); const token = params.get('token') ?? ''; const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (token.length < 20) { setError('This reset link is missing its token. Request a new link to continue.'); return; } if (password !== confirm) { setError('Passwords do not match.'); return; } if (password.length < 12 || !/[A-Z]/.test(password) || !/[a-z]/.test(password) || !/[0-9]/.test(password)) { setError('Use at least 12 characters with uppercase, lowercase, and a number.'); return; } setBusy(true); setError(''); try { await apiRequest('/auth/reset-password', { method: 'POST', body: JSON.stringify({ token, password }) }); router.replace('/login?reason=password-reset'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'This reset link is invalid or expired.'); } finally { setBusy(false); } } return <div className="auth-layout"><div className="auth-brand-row"><Link className="brand" href="/"><ResolveAILogo size="sm" decorative /><span>resolve<span className="brand-accent">ai</span></span></Link><Link className="back-link" href="/">← Back to home</Link></div><main className="auth-card"><div className="auth-heading"><div className="auth-icon">✓</div><div><p className="eyebrow">Account recovery</p><h1>Choose a new password</h1><p>Use a strong password you haven’t used elsewhere.</p></div></div><form onSubmit={submit} noValidate><label htmlFor="new-password">New password<input id="new-password" value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete="new-password" required /></label><p className="password-hint">Use 12+ characters with uppercase, lowercase, and a number.</p><label htmlFor="confirm-password">Confirm new password<input id="confirm-password" value={confirm} onChange={(event) => setConfirm(event.target.value)} type="password" autoComplete="new-password" required /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button auth-submit" type="submit" disabled={busy || token.length < 20}>{busy ? 'Updating…' : 'Update password'} <span aria-hidden="true">↗</span></button></form><p className="auth-switch"><Link href="/login">Back to sign in</Link></p></main><p className="auth-footer">Secure account recovery · ResolveAI</p></div>; }

export default function ResetPasswordPage() { return <Suspense fallback={<div className="auth-layout"><main className="auth-card"><p className="auth-loading">Loading password recovery…</p></main></div>}><ResetPasswordContent /></Suspense>; }
