'use client';

import Link from 'next/link';
import { useSearchParams, useRouter } from 'next/navigation';
import { Suspense, useState } from 'react';
import { apiRequest } from '../api-client';

function ResetPasswordContent() { const params = useSearchParams(); const router = useRouter(); const [token, setToken] = useState(params.get('token') ?? ''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(): Promise<void> { if (password !== confirm) { setError('Passwords do not match.'); return; } if (password.length < 12 || !/[A-Z]/.test(password) || !/[a-z]/.test(password) || !/[0-9]/.test(password)) { setError('Use at least 12 characters with uppercase, lowercase, and a number.'); return; } setBusy(true); setError(''); try { await apiRequest('/auth/reset-password', { method: 'POST', body: JSON.stringify({ token, password }) }); router.replace('/login?reason=password-reset'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'This reset link is invalid or expired.'); } finally { setBusy(false); } } return <div className="auth-layout"><main className="auth-card"><p className="eyebrow">Account recovery</p><h1>Choose a new password</h1><label>Reset token<input value={token} onChange={(event) => setToken(event.target.value)} /></label><label>New password<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete="new-password" /></label><label>Confirm password<input value={confirm} onChange={(event) => setConfirm(event.target.value)} type="password" autoComplete="new-password" /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button auth-submit" type="button" disabled={busy || token.length < 20} onClick={() => void submit()}>{busy ? 'Updating…' : 'Update password'}</button><p className="auth-switch"><Link href="/login">Back to sign in</Link></p></main></div>; }

export default function ResetPasswordPage() { return <Suspense fallback={<div className="auth-layout"><main className="auth-card"><p className="auth-loading">Loading password recovery…</p></main></div>}><ResetPasswordContent /></Suspense>; }
