'use client';

import Link from 'next/link';
import { useCallback, useEffect, useRef, useState, type ChangeEvent, type DragEvent, type FormEvent } from 'react';
import { useDashboard } from '../dashboard-context';
import { apiRequest } from '../../api-client';

type DocumentStatus = 'UPLOADED' | 'PROCESSING' | 'EMBEDDING' | 'READY' | 'FAILED';
type Document = { id: string; name: string; originalFileName: string; mimeType: string; sizeBytes: number; status: DocumentStatus; processingError?: string | null; createdAt: string; processedAt?: string | null; uploadedBy: { firstName: string; lastName: string; email: string } };
type SearchResult = { chunkId: string; chunkIndex: number; content: string; similarityScore: number; document: { id: string; name: string; originalFileName: string; mimeType: string }; characterStart: number | null; characterEnd: number | null; createdAt: string };
type ListResponse = { documents: Document[]; total: number; page: number; pageSize: number };
type SearchResponse = { query: string; results: SearchResult[] };
type AnswerSource = { number: number; documentId: string; documentName: string; chunkIndex: number; contentPreview: string; similarityScore: number; cited: boolean };
type AnswerResponse = { answer: string; sources: AnswerSource[]; provider: string | null; model: string | null; usage: { inputTokens: number; outputTokens: number } };
const formatBytes = (bytes: number): string => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
const formatDate = (value: string): string => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value));
const statusLabel: Record<DocumentStatus, string> = { UPLOADED: 'Queued', PROCESSING: 'Processing', EMBEDDING: 'Embedding', READY: 'Ready', FAILED: 'Failed' };

async function request<T>(path: string, init?: RequestInit): Promise<T> { return apiRequest<T>(path, init); }

export default function Knowledge() {
  const { currentWorkspace, organizationRole, workspaceRole } = useDashboard();
  const inputRef = useRef<HTMLInputElement>(null);
  const [documents, setDocuments] = useState<Document[]>([]);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [dragging, setDragging] = useState(false);
  const [query, setQuery] = useState('');
  const [minimumScore, setMinimumScore] = useState('0.4');
  const [filterDocumentId, setFilterDocumentId] = useState('');
  const [results, setResults] = useState<SearchResult[] | null>(null);
  const [searchError, setSearchError] = useState('');
  const [searching, setSearching] = useState(false);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  const [question, setQuestion] = useState('');
  const [answerResult, setAnswerResult] = useState<AnswerResponse | null>(null);
  const [answerError, setAnswerError] = useState('');
  const [asking, setAsking] = useState(false);
  const canUpload = organizationRole === 'OWNER' || organizationRole === 'ADMIN' || workspaceRole === 'ADMIN' || workspaceRole === 'AGENT';
  const readyDocuments = documents.filter((document) => document.status === 'READY');
  const load = useCallback(async () => { if (!currentWorkspace) return; setLoading(true); setError(''); try { const result = await request<ListResponse>(`/workspaces/${currentWorkspace.id}/knowledge/documents?page=1&pageSize=50${search ? `&search=${encodeURIComponent(search)}` : ''}${status ? `&status=${status}` : ''}`); setDocuments(result.documents); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load knowledge documents.'); } finally { setLoading(false); } }, [currentWorkspace, search, status]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!currentWorkspace || !documents.some((document) => document.status === 'UPLOADED' || document.status === 'PROCESSING' || document.status === 'EMBEDDING')) return; const timer = window.setInterval(() => void load(), 3000); return () => window.clearInterval(timer); }, [currentWorkspace, documents, load]);
  async function upload(file: File): Promise<void> { setUploading(true); setError(''); setNotice(''); const form = new FormData(); form.append('file', file); try { await request<Document>(`/workspaces/${currentWorkspace?.id}/knowledge/documents`, { method: 'POST', body: form }); setNotice(`${file.name} uploaded and queued for processing.`); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to upload document.'); } finally { setUploading(false); } }
  function selectFile(event: ChangeEvent<HTMLInputElement>): void { const file = event.target.files?.[0]; if (file) void upload(file); event.target.value = ''; }
  function drop(event: DragEvent<HTMLDivElement>): void { event.preventDefault(); setDragging(false); const file = event.dataTransfer.files[0]; if (file) void upload(file); }
  async function runSearch(event?: FormEvent): Promise<void> { event?.preventDefault(); if (!currentWorkspace || searching) return; setSearching(true); setSearchError(''); setResults(null); setExpanded(new Set()); try { const result = await request<SearchResponse>(`/workspaces/${currentWorkspace.id}/knowledge/search`, { method: 'POST', body: JSON.stringify({ query, limit: 10, minimumScore: Number(minimumScore), documentIds: filterDocumentId ? [filterDocumentId] : [] }) }); setResults(result.results); } catch (caught) { setSearchError(caught instanceof Error ? caught.message : 'Unable to search the knowledge base.'); } finally { setSearching(false); } }
  function clearSearch(): void { setQuery(''); setResults(null); setSearchError(''); setExpanded(new Set()); }
  function toggleExpanded(id: string): void { setExpanded((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  async function askResolveAi(event?: FormEvent): Promise<void> { event?.preventDefault(); if (!currentWorkspace || asking) return; setAsking(true); setAnswerError(''); setAnswerResult(null); try { const result = await request<AnswerResponse>(`/workspaces/${currentWorkspace.id}/knowledge/answer`, { method: 'POST', body: JSON.stringify({ question, documentIds: filterDocumentId ? [filterDocumentId] : [] }) }); setAnswerResult(result); } catch (caught) { setAnswerError(caught instanceof Error ? caught.message : 'Unable to generate a grounded answer.'); } finally { setAsking(false); } }
  function clearAnswer(): void { setQuestion(''); setAnswerResult(null); setAnswerError(''); }
  return <section className="knowledge-page"><div className="knowledge-intro"><div><p className="eyebrow">Workspace knowledge</p><h2>Your source of truth.</h2><p>Upload the documents your team relies on, then find the most relevant source passages with semantic search.</p></div>{canUpload && <button className="button button-small" type="button" onClick={() => inputRef.current?.click()}>Upload document <span>↗</span></button>}</div>
    <form className="knowledge-answer-panel" onSubmit={(event) => void askResolveAi(event)}><div><p className="eyebrow">Ask ResolveAI</p><h3>Get a grounded answer</h3><p>Answers are generated only from ready documents in this workspace and include source citations.</p></div><div className="knowledge-search-controls"><label htmlFor="grounded-question">Your question</label><div className="knowledge-search-row"><input id="grounded-question" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="How can a customer request a refund?" maxLength={1000} /><button className="button button-small" type="submit" disabled={asking || !question.trim()}>{asking ? 'Thinking…' : 'Ask ResolveAI'}</button>{(answerResult || answerError) && <button className="text-action" type="button" onClick={clearAnswer}>Clear</button>}</div></div></form>
    {answerError && <div className="dashboard-error" role="alert">{answerError}</div>}{answerResult && <section className="knowledge-answer-results" aria-live="polite"><div className="section-heading"><div><p className="eyebrow">Grounded answer</p><h3>Based on workspace knowledge</h3></div><span className="section-hint">Not a generated action</span></div><p className="knowledge-answer-disclaimer">This answer is based only on the retrieved source passages. Verify important decisions against the original documents.</p><div className="knowledge-answer-copy">{answerResult.answer.split(/(\[\d+\])/g).map((part, index) => { const number = Number(part.match(/^\[(\d+)\]$/)?.[1] ?? 0); const source = answerResult.sources.find((candidate) => candidate.number === number); return source ? <Link key={`${part}-${index}`} href={`/dashboard/knowledge/${source.documentId}`} className="knowledge-citation">{part}</Link> : <span key={`${part}-${index}`}>{part}</span>; })}</div>{answerResult.sources.length > 0 && <div className="knowledge-answer-sources"><p className="eyebrow">Sources used</p>{answerResult.sources.map((source) => <Link className="knowledge-answer-source" href={`/dashboard/knowledge/${source.documentId}`} key={source.number}><span><strong>[{source.number}] {source.documentName}</strong><small>Chunk {source.chunkIndex + 1} · {source.contentPreview}</small></span><b>{Math.round(source.similarityScore * 100)}%</b></Link>)}</div>}</section>}
    <form className="knowledge-search-panel" onSubmit={(event) => void runSearch(event)}><div><p className="eyebrow">Semantic search</p><h3>Find a source passage</h3><p>Searches only ready documents in this workspace. Results are source material, not generated answers.</p></div><div className="knowledge-search-controls"><label htmlFor="semantic-query">Search query</label><div className="knowledge-search-row"><input id="semantic-query" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="How can a customer request a refund?" maxLength={1000} /><button className="button button-small" type="submit" disabled={searching || !query.trim()}>{searching ? 'Searching…' : 'Search'}</button>{(results || searchError) && <button className="text-action" type="button" onClick={clearSearch}>Clear</button>}</div><div className="knowledge-search-options"><label htmlFor="minimum-score">Minimum relevance <select id="minimum-score" value={minimumScore} onChange={(event) => setMinimumScore(event.target.value)}><option value="0.4">40%+</option><option value="0.5">50%+</option><option value="0.65">65%+</option><option value="0.8">80%+</option></select></label><label htmlFor="search-document">Source document <select id="search-document" value={filterDocumentId} onChange={(event) => setFilterDocumentId(event.target.value)}><option value="">All ready documents</option>{readyDocuments.map((document) => <option key={document.id} value={document.id}>{document.name}</option>)}</select></label></div></div></form>
    {searchError && <div className="dashboard-error" role="alert">{searchError}</div>}{results && <section className="knowledge-search-results" aria-live="polite"><div className="section-heading"><div><p className="eyebrow">Source passages</p><h3>{results.length ? `${results.length} relevant passage${results.length === 1 ? '' : 's'}` : 'No matching passages'}</h3></div><span className="section-hint">Ranked by relevance</span></div>{results.length === 0 ? <p className="knowledge-search-empty">No ready source passages matched that query. Try a broader question or lower the minimum relevance.</p> : <div className="knowledge-result-list">{results.map((result) => { const isExpanded = expanded.has(result.chunkId); const content = isExpanded ? result.content : result.content.length > 360 ? `${result.content.slice(0, 360)}…` : result.content; return <article className="knowledge-result" key={result.chunkId}><div className="knowledge-result-heading"><div><Link href={`/dashboard/knowledge/${result.document.id}`}><strong>{result.document.name}</strong></Link><span>Chunk {result.chunkIndex + 1} · {result.document.originalFileName}</span></div><b>{Math.round(result.similarityScore * 100)}%</b></div><p>{content}</p><div className="knowledge-result-footer"><span>{result.characterStart ?? 0}–{result.characterEnd ?? 0} characters · {result.document.mimeType}</span>{result.content.length > 360 && <button className="text-action" type="button" onClick={() => toggleExpanded(result.chunkId)}>{isExpanded ? 'Show less' : 'Read more'}</button>}</div></article>; })}</div>}</section>}
    {canUpload && <><input ref={inputRef} className="visually-hidden" type="file" accept="application/pdf,text/plain,text/markdown,text/x-markdown" onChange={selectFile} /><div className={`knowledge-dropzone${dragging ? ' is-dragging' : ''}`} onDragEnter={(event) => { event.preventDefault(); setDragging(true); }} onDragOver={(event) => event.preventDefault()} onDragLeave={() => setDragging(false)} onDrop={drop}><div className="knowledge-drop-icon">↑</div><strong>{uploading ? 'Uploading document…' : 'Drop a document here or browse'}</strong><span>PDF, TXT, or Markdown · up to 10 MB</span><button className="text-action" type="button" onClick={() => inputRef.current?.click()} disabled={uploading}>Choose file</button></div></>}
    {notice && <p className="team-success" role="status">{notice}</p>}{error && <div className="dashboard-error" role="alert"><span>{error}</span><button type="button" onClick={() => void load()}>Try again</button></div>}<div className="knowledge-toolbar"><div><p className="eyebrow">Document library</p><h3>{documents.length ? `${documents.length} document${documents.length === 1 ? '' : 's'}` : 'No documents yet'}</h3></div><div className="knowledge-filters"><label className="visually-hidden" htmlFor="knowledge-search">Filter documents</label><input id="knowledge-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Filter documents" /><label className="visually-hidden" htmlFor="knowledge-status">Filter status</label><select id="knowledge-status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option value="READY">Ready</option><option value="PROCESSING">Processing</option><option value="EMBEDDING">Embedding</option><option value="FAILED">Failed</option></select></div></div>{loading ? <p className="dashboard-inline-status">Loading your documents…</p> : documents.length === 0 ? <div className="knowledge-empty"><div className="empty-state-icon">✦</div><h3>No knowledge documents yet.</h3><p>Upload a guide, FAQ, or policy to start building this workspace’s source of truth.</p>{canUpload && <button className="button button-small" type="button" onClick={() => inputRef.current?.click()}>Upload first document <span>↗</span></button>}</div> : <div className="knowledge-list">{documents.map((document) => <Link className="knowledge-row" href={`/dashboard/knowledge/${document.id}`} key={document.id}><span className="file-icon">{document.mimeType === 'application/pdf' ? 'PDF' : 'TXT'}</span><span className="knowledge-name"><strong>{document.name}</strong><small>{document.originalFileName} · {formatBytes(document.sizeBytes)}</small></span><span className="knowledge-uploader">{document.uploadedBy.firstName} {document.uploadedBy.lastName}<small>{formatDate(document.createdAt)}</small></span><span className={`document-status status-${document.status.toLowerCase()}`}>{statusLabel[document.status]}</span><span className="knowledge-arrow">→</span></Link>)}</div>}</section>;
}
