CREATE TYPE "WidgetMessageRole" AS ENUM ('USER', 'ASSISTANT', 'HUMAN', 'SYSTEM');
CREATE TYPE "SupportConversationStatus" AS ENUM ('OPEN', 'PENDING', 'RESOLVED');
CREATE TYPE "SupportConversationMode" AS ENUM ('AI', 'HUMAN');
CREATE TYPE "SupportConversationPriority" AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT');
CREATE TYPE "SupportConversationSource" AS ENUM ('WIDGET', 'DASHBOARD', 'API');
DROP INDEX "WidgetConversation_workspaceId_createdAt_idx";
ALTER TABLE "WidgetConversation" ADD COLUMN "assignedUserId" UUID, ADD COLUMN "lastMessageAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD COLUMN "mode" "SupportConversationMode" NOT NULL DEFAULT 'AI', ADD COLUMN "priority" "SupportConversationPriority" NOT NULL DEFAULT 'NORMAL', ADD COLUMN "resolvedAt" TIMESTAMP(3), ADD COLUMN "resolvedByUserId" UUID, ADD COLUMN "source" "SupportConversationSource" NOT NULL DEFAULT 'WIDGET', ADD COLUMN "status" "SupportConversationStatus" NOT NULL DEFAULT 'OPEN', ADD COLUMN "visitorPageUrl" TEXT, ADD COLUMN "visitorReferrer" TEXT;
ALTER TABLE "WidgetMessage" ADD COLUMN "clientMessageId" TEXT;
ALTER TABLE "WidgetMessage" ALTER COLUMN "role" TYPE "WidgetMessageRole" USING ("role"::text::"WidgetMessageRole");
CREATE TABLE "WidgetConversationRead" ("id" UUID NOT NULL, "conversationId" UUID NOT NULL, "workspaceId" UUID NOT NULL, "userId" UUID NOT NULL, "readAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "WidgetConversationRead_pkey" PRIMARY KEY ("id"));
CREATE TABLE "WidgetConversationNote" ("id" UUID NOT NULL, "conversationId" UUID NOT NULL, "workspaceId" UUID NOT NULL, "authorUserId" UUID NOT NULL, "content" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "WidgetConversationNote_pkey" PRIMARY KEY ("id"));
CREATE INDEX "WidgetConversationRead_workspaceId_userId_readAt_idx" ON "WidgetConversationRead"("workspaceId", "userId", "readAt");
CREATE UNIQUE INDEX "WidgetConversationRead_conversationId_userId_key" ON "WidgetConversationRead"("conversationId", "userId");
CREATE INDEX "WidgetConversationNote_conversationId_createdAt_idx" ON "WidgetConversationNote"("conversationId", "createdAt");
CREATE INDEX "WidgetConversation_workspaceId_status_lastMessageAt_idx" ON "WidgetConversation"("workspaceId", "status", "lastMessageAt");
CREATE INDEX "WidgetConversation_workspaceId_assignedUserId_idx" ON "WidgetConversation"("workspaceId", "assignedUserId");
CREATE UNIQUE INDEX "WidgetMessage_conversationId_clientMessageId_key" ON "WidgetMessage"("conversationId", "clientMessageId");
ALTER TABLE "WidgetConversation" ADD CONSTRAINT "WidgetConversation_assignedUserId_fkey" FOREIGN KEY ("assignedUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE, ADD CONSTRAINT "WidgetConversation_resolvedByUserId_fkey" FOREIGN KEY ("resolvedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "WidgetConversationRead" ADD CONSTRAINT "WidgetConversationRead_conversationId_workspaceId_fkey" FOREIGN KEY ("conversationId", "workspaceId") REFERENCES "WidgetConversation"("id", "workspaceId") ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT "WidgetConversationRead_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT "WidgetConversationRead_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WidgetConversationNote" ADD CONSTRAINT "WidgetConversationNote_conversationId_workspaceId_fkey" FOREIGN KEY ("conversationId", "workspaceId") REFERENCES "WidgetConversation"("id", "workspaceId") ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT "WidgetConversationNote_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT "WidgetConversationNote_authorUserId_fkey" FOREIGN KEY ("authorUserId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
