export const ORGANIZATION_ROLES = ['OWNER', 'ADMIN', 'MEMBER'] as const;
export const WORKSPACE_ROLES = ['ADMIN', 'AGENT', 'VIEWER'] as const;
export type OrganizationRole = (typeof ORGANIZATION_ROLES)[number];
export type WorkspaceRole = (typeof WORKSPACE_ROLES)[number];
export type ApiSuccess<T> = { success: true; message: string; data: T };
export type ApiFailure = { success: false; message: string; error: { code: string; details: readonly unknown[] } };
export type ApiResponse<T> = ApiSuccess<T> | ApiFailure;

export type SafeLogLevel = 'debug' | 'info' | 'warn' | 'error';
export type SafeLogEvent = { level?: SafeLogLevel; service: string; environment?: string; event: string; requestId?: string; userId?: string; organizationId?: string; workspaceId?: string; route?: string; method?: string; statusCode?: number; durationMs?: number; errorCode?: string; message?: string; [key: string]: unknown };
export function writeSafeLog(event: SafeLogEvent): void { const safe = Object.fromEntries(Object.entries(event).filter(([key, value]) => { if (['password','passwordHash','token','accessToken','refreshToken','cookie','authorization','secret','apiKey','content','body'].some((part) => key.toLowerCase().includes(part))) return false; return value !== undefined && !(typeof value === 'string' && value.length > 500); })); const line = JSON.stringify({ timestamp: new Date().toISOString(), ...safe }); const level = event.level ?? 'info'; if (level === 'error') console.error(line); else if (level === 'warn') console.warn(line); else if (level === 'debug') console.debug(line); else console.info(line); }
export function isValidRequestId(value: unknown): value is string { return typeof value === 'string' && /^[A-Za-z0-9._:-]{1,100}$/.test(value); }
const ipv4Mapped = /^::ffff:(\d+\.\d+\.\d+\.\d+)$/i;
const blockedIpv4 = (value: string): boolean => { const parts = value.split('.').map(Number); if (parts.length !== 4 || parts.some((part) => !Number.isInteger(part) || part < 0 || part > 255)) return true; const a = parts[0] ?? 0; const b = parts[1] ?? 0; return a === 0 || a === 10 || a === 100 && b >= 64 && b <= 127 || a === 127 || a === 169 && b === 254 || a === 172 && b >= 16 && b <= 31 || a === 192 && (b === 0 || b === 168); };
export function isPrivateOrReservedAddress(value: string): boolean { const normalized = value.toLowerCase().replace(/%.*$/, ''); const mapped = normalized.match(ipv4Mapped)?.[1]; if (mapped) return blockedIpv4(mapped); if (/^\d+\.\d+\.\d+\.\d+$/.test(normalized)) return blockedIpv4(normalized); if (!normalized.includes(':')) return true; if (normalized === '::1' || normalized === '::' || normalized.startsWith('fc') || normalized.startsWith('fd') || normalized.startsWith('fe80:')) return true; const groups = normalized.split(':'); const tail = groups.slice(-2).map((group) => Number.parseInt(group || '0', 16)); if (normalized.startsWith('64:ff9b:') && tail.length === 2) { const first = tail[0] ?? 0; const second = tail[1] ?? 0; return blockedIpv4(`${first >>> 8}.${first & 255}.${second >>> 8}.${second & 255}`); } return false; }
export function isBlockedHostname(hostname: string): boolean { const value = hostname.toLowerCase().replace(/\.$/, ''); return value === 'localhost' || value.endsWith('.localhost') || value === 'metadata.google.internal' || value === 'instance-data.ec2.internal'; }
