import { ConflictException, ForbiddenException, Inject, Injectable, NotFoundException, Optional } from '@nestjs/common';
import type { Prisma, PrismaClient } from '@resolveai/database';
// Nest dependency injection needs the service constructor at runtime.
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import { WorkspaceAccessService } from '../workspace-access/workspace-access.service';
// Nest dependency injection needs this constructor at runtime.
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import { WebhookEventsService } from '../webhooks/webhook-events.service';
import type { InboxAssignmentDto, InboxListDto, InboxMessageDto, InboxNoteDto, InboxPriorityDto, InboxStatusDto } from './inbox.dto';
// Nest dependency injection needs this constructor at runtime.
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import { AuditLogService } from '../audit-log/audit-log.service';

const canManage = (access: { organizationRole: string; workspaceRole: string }) => ['OWNER', 'ADMIN'].includes(access.organizationRole) || ['ADMIN', 'AGENT'].includes(access.workspaceRole);

@Injectable()
export class InboxService {
  constructor(@Inject('PRISMA') private readonly db: PrismaClient, private readonly access: WorkspaceAccessService, @Optional() private readonly audit?: AuditLogService, @Optional() private readonly events?: WebhookEventsService) {}
  private async member(userId: string, workspaceId: string, manage = false) { const result = await this.access.getAccess(userId, workspaceId); if (manage && !canManage(result)) throw new ForbiddenException('Insufficient workspace permissions'); return result; }
  private where(workspaceId: string, id: string) { return { id, workspaceId }; }
  private async conversation(userId: string, workspaceId: string, id: string) { await this.member(userId, workspaceId); const result = await this.db.widgetConversation.findFirst({ where: this.where(workspaceId, id), include: { assignedUser: { select: { id: true, firstName: true, lastName: true, email: true } }, messages: { orderBy: { createdAt: 'asc' }, include: { sources: { orderBy: { sourceNumber: 'asc' } } } }, notes: { orderBy: { createdAt: 'asc' }, include: { author: { select: { id: true, firstName: true, lastName: true, email: true } } } } } }); if (!result) throw new NotFoundException('Inbox conversation not found'); return result; }
  private view(item: { id: string; title: string; status: string; mode: string; priority: string; source: string; visitorPageUrl: string | null; visitorReferrer: string | null; createdAt: Date; lastMessageAt: Date; resolvedAt: Date | null; agentNameSnapshot: string; assignedUser?: unknown; messages?: Array<{ id: string; role: string; content: string; createdAt: Date }> }, unread = false) { const last = item.messages?.at(-1); return { id: item.id, title: item.title, status: item.status, mode: item.mode, priority: item.priority, source: item.source, visitorPageUrl: item.visitorPageUrl, visitorReferrer: item.visitorReferrer, createdAt: item.createdAt, lastMessageAt: item.lastMessageAt, resolvedAt: item.resolvedAt, unread, assignedUser: item.assignedUser, agentName: item.agentNameSnapshot, lastMessage: last ? { id: last.id, role: last.role, content: last.content, createdAt: last.createdAt } : null }; }
  async list(userId: string, workspaceId: string, query: InboxListDto) { const access = await this.member(userId, workspaceId); const where: Prisma.WidgetConversationWhereInput = { workspaceId, ...(query.status ? { status: query.status } : {}), ...(query.assignment === 'mine' ? { assignedUserId: userId } : query.assignment === 'unassigned' ? { assignedUserId: null } : {}), ...(query.search ? { OR: [{ title: { contains: query.search, mode: 'insensitive' } }, { messages: { some: { content: { contains: query.search, mode: 'insensitive' } } } }] } : {}) }; const rows = await this.db.widgetConversation.findMany({ where, orderBy: { lastMessageAt: 'desc' }, take: 100, include: { assignedUser: { select: { id: true, firstName: true, lastName: true, email: true } }, messages: { orderBy: { createdAt: 'desc' }, take: 1 } } }); const reads = await this.db.widgetConversationRead.findMany({ where: { workspaceId, userId, conversationId: { in: rows.map((row) => row.id) } } }); const readMap = new Map(reads.map((read) => [read.conversationId, read.readAt])); const items = rows.map((row) => this.view(row, !readMap.has(row.id) || row.messages[0]?.role === 'USER' && row.messages[0].createdAt > readMap.get(row.id)!)); return { items, unreadCount: items.filter((item) => item.unread).length, canManage: canManage(access) }; }
  async detail(userId: string, workspaceId: string, id: string) { const row = await this.conversation(userId, workspaceId, id); return { ...this.view(row), messages: row.messages.map((message) => ({ id: message.id, role: message.role, content: message.content, status: message.status, createdAt: message.createdAt, sources: message.sources.map((source) => ({ number: source.sourceNumber, documentName: source.documentNameSnapshot, contentPreview: source.contentPreview, cited: source.cited })) })), notes: row.notes }; }
  async markRead(userId: string, workspaceId: string, id: string) { await this.conversation(userId, workspaceId, id); await this.db.widgetConversationRead.upsert({ where: { conversationId_userId: { conversationId: id, userId } }, update: { readAt: new Date() }, create: { conversationId: id, workspaceId, userId } }); return { success: true }; }
  async assign(userId: string, workspaceId: string, id: string, dto: InboxAssignmentDto) { await this.member(userId, workspaceId, true); if (dto.assignedUserId) { await this.access.getAccess(dto.assignedUserId, workspaceId); } return this.db.widgetConversation.update({ where: { id_workspaceId: { id, workspaceId } }, data: { assignedUserId: dto.assignedUserId ?? null } }); }
  async priority(userId: string, workspaceId: string, id: string, dto: InboxPriorityDto) { await this.member(userId, workspaceId, true); return this.db.widgetConversation.update({ where: { id_workspaceId: { id, workspaceId } }, data: { priority: dto.priority } }); }
  async status(userId: string, workspaceId: string, id: string, dto: InboxStatusDto) { const access = await this.member(userId, workspaceId, true); const result = await this.db.widgetConversation.update({ where: { id_workspaceId: { id, workspaceId } }, data: { status: dto.status, resolvedAt: dto.status === 'RESOLVED' ? new Date() : null, resolvedByUserId: dto.status === 'RESOLVED' ? userId : null } }); await this.audit?.record({ organizationId: access.organizationId, workspaceId, actorUserId: userId, action: 'conversation.status_changed', targetType: 'widget_conversation', targetId: id, metadata: { status: dto.status } }); void this.events?.publish(workspaceId, 'conversation.closed', { conversationId: id, status: dto.status, userId }, 'conversation.status:' + workspaceId + ':' + id + ':' + Date.now()); return result; }
  async takeover(userId: string, workspaceId: string, id: string) { const access = await this.member(userId, workspaceId, true); const changed = await this.db.widgetConversation.updateMany({ where: { id, workspaceId, mode: 'AI', status: { not: 'RESOLVED' } }, data: { mode: 'HUMAN', assignedUserId: userId, status: 'OPEN', lastMessageAt: new Date() } }); if (changed.count !== 1) throw new ConflictException('Conversation is already being handled by a teammate'); await this.db.widgetMessage.create({ data: { conversationId: id, workspaceId, role: 'SYSTEM', content: 'A support teammate has joined the conversation.', status: 'COMPLETE' } }); await this.audit?.record({ organizationId: access.organizationId, workspaceId, actorUserId: userId, action: 'conversation.human_takeover', targetType: 'widget_conversation', targetId: id }); void this.events?.publish(workspaceId, 'conversation.takeover', { conversationId: id, userId }, 'conversation.takeover:' + workspaceId + ':' + id + ':' + Date.now()); return this.detail(userId, workspaceId, id); }
  async returnToAi(userId: string, workspaceId: string, id: string) { const access = await this.member(userId, workspaceId, true); const changed = await this.db.widgetConversation.updateMany({ where: { id, workspaceId, mode: 'HUMAN' }, data: { mode: 'AI', status: 'OPEN', assignedUserId: null, generationLockAt: null, lastMessageAt: new Date() } }); if (changed.count !== 1) throw new ConflictException('Conversation is already handled by AI'); await this.audit?.record({ organizationId: access.organizationId, workspaceId, actorUserId: userId, action: 'conversation.returned_to_ai', targetType: 'widget_conversation', targetId: id }); void this.events?.publish(workspaceId, 'conversation.returned_to_ai', { conversationId: id, userId }, 'conversation.returned_to_ai:' + workspaceId + ':' + id + ':' + Date.now()); return this.detail(userId, workspaceId, id); }
  async reply(userId: string, workspaceId: string, id: string, dto: InboxMessageDto) { await this.member(userId, workspaceId, true); const content = dto.content.trim(); const existing = dto.clientMessageId ? await this.db.widgetMessage.findFirst({ where: { conversationId: id, workspaceId, clientMessageId: dto.clientMessageId } }) : null; if (existing) return existing; const conversation = await this.db.widgetConversation.findFirst({ where: this.where(workspaceId, id) }); if (!conversation) throw new NotFoundException('Inbox conversation not found'); return this.db.$transaction(async (tx) => { const changed = await tx.widgetConversation.updateMany({ where: { id, workspaceId, mode: 'HUMAN', status: { not: 'RESOLVED' } }, data: { status: 'OPEN', lastMessageAt: new Date() } }); if (changed.count !== 1) throw new ConflictException('Take over the conversation before replying'); return tx.widgetMessage.create({ data: { conversationId: id, workspaceId, role: 'HUMAN', content, status: 'COMPLETE', clientMessageId: dto.clientMessageId } }); }); }
  async note(userId: string, workspaceId: string, id: string, dto: InboxNoteDto) { await this.member(userId, workspaceId, true); await this.conversation(userId, workspaceId, id); return this.db.widgetConversationNote.create({ data: { conversationId: id, workspaceId, authorUserId: userId, content: dto.content.trim() }, include: { author: { select: { id: true, firstName: true, lastName: true, email: true } } } }); }
}
