import { createCipheriv, createHash, randomBytes } from 'node:crypto'; import { lookup } from 'node:dns/promises'; import { isIP } from 'node:net';
import { ConflictException, ForbiddenException, Inject, Injectable, NotFoundException } from '@nestjs/common'; import type { PrismaClient } from '@resolveai/database'; // Nest dependency injection needs this constructor at runtime.
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import { WorkspaceAccessService } from '../workspace-access/workspace-access.service';
const privateHost=(host:string):boolean=>{const h=host.toLowerCase(); if(h==='localhost'||h.endsWith('.localhost')||h==='metadata.google.internal')return true; const v=isIP(h); if(v===4){const [a,b=0]=h.split('.').map(Number);return a===10||a===127||a===169&&b===254||a===192&&b===168||a===172&&b>=16&&b<=31;} return v===6&&(h==='::1'||h.startsWith('fc')||h.startsWith('fd')||h.startsWith('fe80:'));};
const key=():Buffer=>{const value=process.env.WEBHOOK_ENCRYPTION_KEY; if(!value) throw new ConflictException('Webhook encryption is not configured'); return createHash('sha256').update(value).digest();};
const encrypt=(secret:string):string=>{const iv=randomBytes(12); const cipher=createCipheriv('aes-256-gcm',key(),iv); const encrypted=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]); return Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString('base64url');};
@Injectable() export class WebhooksService { constructor(@Inject('PRISMA') private readonly db: PrismaClient, private readonly access: WorkspaceAccessService) {} async authorizeManager(userId:string,workspaceId:string){const a=await this.access.getAccess(userId,workspaceId);if(a.organizationRole!=='OWNER'&&a.organizationRole!=='ADMIN'&&a.workspaceRole!=='ADMIN')throw new ForbiddenException('Only workspace managers can manage webhooks');}
 private async safeUrl(value:string){let url:URL;try{url=new URL(value);}catch{throw new ConflictException('Enter a valid webhook URL');}if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw new ConflictException('Webhook URL must be a public HTTP or HTTPS URL');const addresses=await lookup(url.hostname,{all:true});if(!addresses.length||addresses.some((a)=>privateHost(a.address)))throw new ConflictException('Webhook URL cannot target a private or local network');return url.toString();}
 async list(userId:string,workspaceId:string){await this.access.assertMember(userId,workspaceId);return this.db.outboundWebhook.findMany({where:{workspaceId},orderBy:{createdAt:'desc'},select:{id:true,name:true,url:true,events:true,enabled:true,createdAt:true,updatedAt:true}});}
 async create(userId:string,workspaceId:string,dto:{name:string;url:string;events:string[]}){await this.authorizeManager(userId,workspaceId);const url=await this.safeUrl(dto.url);const secret=randomBytes(32).toString('base64url');try{const hook=await this.db.outboundWebhook.create({data:{workspaceId,createdByUserId:userId,name:dto.name.trim(),url,events:dto.events,secretCiphertext:encrypt(secret)}});return{id:hook.id,name:hook.name,url:hook.url,events:hook.events,enabled:hook.enabled,secret};}catch(error){if((error as {code?:string}).code==='P2002')throw new ConflictException('A webhook with this name already exists');throw error;}}
 async update(userId:string,workspaceId:string,id:string,dto:{enabled?:boolean;events?:string[]}){await this.authorizeManager(userId,workspaceId);const hook=await this.db.outboundWebhook.findFirst({where:{id,workspaceId}});if(!hook)throw new NotFoundException('Webhook not found');return this.db.outboundWebhook.update({where:{id},data:dto,select:{id:true,name:true,url:true,events:true,enabled:true,createdAt:true,updatedAt:true}});}
 async remove(userId:string,workspaceId:string,id:string){await this.authorizeManager(userId,workspaceId);const hook=await this.db.outboundWebhook.findFirst({where:{id,workspaceId}});if(!hook)throw new NotFoundException('Webhook not found');await this.db.outboundWebhook.delete({where:{id}});}
}
