import { Inject, Injectable } from '@nestjs/common'; import { Queue } from 'bullmq'; import type { Prisma, PrismaClient } from '@resolveai/database';
import { redisConnectionOptionsFromEnv } from '@resolveai/config';
export const WEBHOOK_QUEUE = 'webhook-delivery';
type SafePayload = Record<string, unknown>;
const safePayload = (payload: SafePayload): SafePayload => Object.fromEntries(Object.entries(payload).filter(([key]) => !/(password|token|secret|authorization|cookie|content|body|messages|extracted)/i.test(key)).slice(0, 30));
@Injectable() export class WebhookEventsService { private readonly queue = new Queue(WEBHOOK_QUEUE, { connection: redisConnectionOptionsFromEnv() }); constructor(@Inject('PRISMA') private readonly db: PrismaClient) {}
 async publish(workspaceId: string, eventType: string, payload: SafePayload, eventKey = eventType + ':' + workspaceId + ':' + Date.now()) { const event = await this.db.webhookEvent.upsert({ where: { eventKey }, update: {}, create: { workspaceId, eventKey, eventType, payload: safePayload(payload) as Prisma.InputJsonValue } }); const hooks = await this.db.outboundWebhook.findMany({ where: { workspaceId, enabled: true, events: { has: eventType } }, select: { id: true } }); const deliveries = await Promise.all(hooks.map((hook) => this.db.webhookDelivery.upsert({ where: { webhookId_eventId: { webhookId: hook.id, eventId: event.id } }, update: {}, create: { webhookId: hook.id, workspaceId, eventId: event.id, eventType, payload: event.payload as Prisma.InputJsonValue } }))); await Promise.all(deliveries.map((delivery) => this.queue.add('deliver-webhook', { deliveryId: delivery.id }, { jobId: delivery.id, attempts: 5, backoff: { type: 'exponential', delay: 1000 }, removeOnComplete: 100, removeOnFail: 100 }))); return { eventId: event.id, deliveryIds: deliveries.map((delivery) => delivery.id) }; }
 async enqueueDelivery(deliveryId: string): Promise<void> { await this.queue.add('deliver-webhook', { deliveryId }, { jobId: deliveryId, attempts: 5, backoff: { type: 'exponential', delay: 1000 }, removeOnComplete: 100, removeOnFail: 100 }); }
 async listDeliveries(workspaceId: string, webhookId: string) { return this.db.webhookDelivery.findMany({ where: { workspaceId, webhookId }, orderBy: { createdAt: 'desc' }, take: 50, select: { id: true, eventId: true, eventType: true, status: true, attempts: true, responseStatus: true, responseBody: true, durationMs: true, errorCategory: true, deliveredAt: true, createdAt: true } }); }
 async retryDelivery(workspaceId: string, webhookId: string, deliveryId: string) { const delivery = await this.db.webhookDelivery.findFirst({ where: { id: deliveryId, webhookId, workspaceId } }); if (!delivery) throw new Error('Webhook delivery not found'); if (delivery.status === 'SUCCEEDED') return { id: delivery.id, status: delivery.status }; await this.db.webhookDelivery.update({ where: { id: delivery.id }, data: { status: 'QUEUED', errorCategory: null, nextAttemptAt: null } }); await this.enqueueDelivery(delivery.id); return { id: delivery.id, status: 'QUEUED' }; }
 async test(userId: string, workspaceId: string, webhookId: string) { const hook = await this.db.outboundWebhook.findFirst({ where: { id: webhookId, workspaceId, enabled: true }, select: { id: true, events: true } }); if (!hook) throw new Error('Webhook not found or disabled'); const event = await this.db.webhookEvent.create({ data: { workspaceId, eventKey: 'test:' + webhookId + ':' + Date.now(), eventType: 'webhook.test', payload: { source: 'dashboard', test: true } } }); const delivery = await this.db.webhookDelivery.create({ data: { webhookId, workspaceId, eventId: event.id, eventType: 'webhook.test', payload: event.payload as Prisma.InputJsonValue } }); await this.enqueueDelivery(delivery.id); return { deliveryId: delivery.id, status: 'QUEUED' }; }
 async onModuleDestroy() { await this.queue.close(); }
}
