'use client';

import { useEffect, useState } from 'react';
import { apiRequest } from '../../../api-client';
import { useDashboard } from '../../dashboard-context';

const slugify = (value: string): string => value.trim().toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/[\s-]+/g, '-').replace(/^-+|-+$/g, '');

export default function GeneralSettings() {
  const { currentOrganization, currentWorkspace, loading, error: dashboardError, reload } = useDashboard();
  const [organizationName, setOrganizationName] = useState(''); const [organizationSlug, setOrganizationSlug] = useState(''); const [workspaceName, setWorkspaceName] = useState(''); const [workspaceSlug, setWorkspaceSlug] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { if (currentOrganization) { setOrganizationName(currentOrganization.name); setOrganizationSlug(currentOrganization.slug); } if (currentWorkspace) { setWorkspaceName(currentWorkspace.name); setWorkspaceSlug(currentWorkspace.slug); } }, [currentOrganization, currentWorkspace]);
  async function save(event: React.FormEvent): Promise<void> { event.preventDefault(); if (!currentOrganization || !currentWorkspace) return; setSaving(true); setError(''); setMessage(''); try { await apiRequest(`/organizations/${currentOrganization.id}`, { method: 'PATCH', body: JSON.stringify({ name: organizationName.trim(), slug: organizationSlug.trim() || slugify(organizationName) }) }); await apiRequest(`/workspaces/${currentWorkspace.id}`, { method: 'PATCH', body: JSON.stringify({ name: workspaceName.trim(), slug: workspaceSlug.trim() || slugify(workspaceName) }) }); setMessage('Settings saved.'); await reload(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to save settings.'); } finally { setSaving(false); } }
  if (loading) return <section className="settings-page"><p className="dashboard-inline-status">Loading settings…</p></section>;
  if (dashboardError) return <section className="settings-page"><div className="dashboard-error" role="alert">{dashboardError}<button type="button" onClick={() => void reload()}>Try again</button></div></section>;
  return <section className="settings-page"><div className="settings-intro"><p className="eyebrow">General settings</p><h2>Workspace details</h2><p>Keep organization and workspace information accurate for your team and customers.</p></div>{(error || message) && <p className={error ? 'dashboard-error' : 'team-success'} role={error ? 'alert' : 'status'}>{error || message}</p>}<form className="settings-form" onSubmit={(event) => void save(event)}><div className="settings-card"><p className="eyebrow">Organization</p><label>Name<input value={organizationName} onChange={(event) => setOrganizationName(event.target.value)} minLength={2} required /></label><label>Slug<input value={organizationSlug} onChange={(event) => setOrganizationSlug(event.target.value)} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /><small>Used in internal links and identifiers.</small></label></div><div className="settings-card"><p className="eyebrow">Workspace</p><label>Name<input value={workspaceName} onChange={(event) => setWorkspaceName(event.target.value)} minLength={2} required /></label><label>Slug<input value={workspaceSlug} onChange={(event) => setWorkspaceSlug(event.target.value)} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label></div><button className="button button-small" type="submit" disabled={saving || !currentOrganization || !currentWorkspace}>{saving ? 'Saving…' : 'Save changes'}</button></form></section>;
}
