'use client';

import { useEffect, useState, type FormEvent } from 'react';
import { apiRequest } from '../../../api-client';
import { useDashboard } from '../../dashboard-context';

const slugify = (value: string): string => value.trim().toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/[\s-]+/g, '-').replace(/^-+|-+$/g, '');

type FormState = { organizationName: string; organizationSlug: string; workspaceName: string; workspaceSlug: string };
const empty: FormState = { organizationName: '', organizationSlug: '', workspaceName: '', workspaceSlug: '' };

export default function GeneralSettings() {
  const { currentOrganization, currentWorkspace, loading, error: dashboardError, reload } = useDashboard();
  const [form, setForm] = useState<FormState>(empty); const [savedForm, setSavedForm] = useState<FormState>(empty); const [saving, setSaving] = useState(false); const [dirty, setDirty] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { const next = { organizationName: currentOrganization?.name ?? '', organizationSlug: currentOrganization?.slug ?? '', workspaceName: currentWorkspace?.name ?? '', workspaceSlug: currentWorkspace?.slug ?? '' }; setForm(next); setSavedForm(next); setDirty(false); }, [currentOrganization, currentWorkspace]);
  useEffect(() => { const handle = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', handle); return () => window.removeEventListener('beforeunload', handle); }, [dirty]);
  function update(key: keyof FormState, value: string): void { setForm((current) => ({ ...current, [key]: value })); setDirty(true); setMessage(''); setError(''); }
  function cancel(): void { setForm(savedForm); setDirty(false); setError(''); setMessage('Changes discarded.'); }
  async function save(event: FormEvent): Promise<void> { event.preventDefault(); if (!currentOrganization || !currentWorkspace) return; const organizationName = form.organizationName.trim(); const workspaceName = form.workspaceName.trim(); const organizationSlug = form.organizationSlug.trim() || slugify(organizationName); const workspaceSlug = form.workspaceSlug.trim() || slugify(workspaceName); if (organizationName.length < 2 || workspaceName.length < 2 || !organizationSlug || !workspaceSlug) { setError('Enter valid organization and workspace names and slugs.'); return; } setSaving(true); setError(''); setMessage(''); try { await apiRequest(`/organizations/${currentOrganization.id}`, { method: 'PATCH', body: JSON.stringify({ name: organizationName, slug: organizationSlug }) }); await apiRequest(`/workspaces/${currentWorkspace.id}`, { method: 'PATCH', body: JSON.stringify({ name: workspaceName, slug: workspaceSlug }) }); const next = { organizationName, organizationSlug, workspaceName, workspaceSlug }; setForm(next); setSavedForm(next); setDirty(false); setMessage('Settings saved.'); await reload(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to save settings.'); } finally { setSaving(false); } }
  if (loading) return <section className="settings-page"><p className="dashboard-inline-status">Loading settings…</p></section>;
  if (dashboardError) return <section className="settings-page"><div className="dashboard-error" role="alert">{dashboardError}<button type="button" onClick={() => void reload()}>Try again</button></div></section>;
  return <section className="settings-page"><div className="settings-intro"><p className="eyebrow">General settings</p><h2>Workspace details</h2><p>Keep organization and workspace information accurate for your team and customers.</p></div>{(error || message) && <p className={error ? 'dashboard-error' : 'team-success'} role={error ? 'alert' : 'status'}>{error || message}</p>}<form className="settings-form" onSubmit={(event) => void save(event)}><div className="settings-card"><p className="eyebrow">Organization</p><label>Name<input value={form.organizationName} onChange={(event) => update('organizationName', event.target.value)} minLength={2} required /></label><label>Slug<input value={form.organizationSlug} onChange={(event) => update('organizationSlug', event.target.value)} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /><small>Lowercase letters, numbers, and hyphens only.</small></label></div><div className="settings-card"><p className="eyebrow">Workspace</p><label>Name<input value={form.workspaceName} onChange={(event) => update('workspaceName', event.target.value)} minLength={2} required /></label><label>Slug<input value={form.workspaceSlug} onChange={(event) => update('workspaceSlug', event.target.value)} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label></div><div className="settings-actions"><button className="button button-ghost button-small" type="button" onClick={cancel} disabled={!dirty || saving}>Cancel</button><button className="button button-small" type="submit" disabled={saving || !dirty || !currentOrganization || !currentWorkspace}>{saving ? 'Saving…' : 'Save changes'}</button></div></form></section>;
}
